---
# Oracle Database 11.2.0.2 Express Edition configuration file
#
# This file will be overwritten on updates, so it is recommended to make a copy
# of this file called config.local.yaml, then make changes in config.local.yaml.
#
# To change a parameter, uncomment it and set it to the desired value.
# All commented parameters will retain their default values.

# VM name
#VM_NAME: 'oracle11g-xe-vagrant'

# Memory for the VM (in MB, 2048 MB = 2 GB)
#VM_MEMORY: 2048

# VM time zone
# If not specified, will be set to match host time zone (if possible)
# Can use time zone name (e.g., 'America/Los_Angeles')
# or an offset from GMT (e.g., 'Etc/GMT-2')
#VM_SYSTEM_TIMEZONE: ''

# Listener port
#VM_LISTENER_PORT: 1521

# Oracle Database password for SYS and SYSTEM accounts
# If left blank, the password will be generated automatically
#VM_ORACLE_PWD: ''
