#!/usr/bin/env bash
#------------------------------------------------------------------------------
# LICENSE UPL 1.0
# Copyright (c) 1982-2026 Oracle and/or its affiliates. All rights reserved.
#
# setup.sh
#   Orchestrator for the Oracle Data Guard two-node provisioning flow.
#   Invoked by Vagrantfile on both primary and standby hosts.
#------------------------------------------------------------------------------

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

SCRIPT_DIR="/vagrant/scripts"

# Environment vars passed in by Vagrantfile (env: { ... }):
#   PROVIDER BOX_DISK_NUM VM1_NAME VM2_NAME SYSTEM_TIMEZONE PREFIX_NAME
#   DB_SOFTWARE DB_SOFTWARE_VER ORA_LANGUAGES DOMAIN
#   NODE1_PUBLIC_IP NODE2_PUBLIC_IP NODE1_PRIV_IP NODE2_PRIV_IP
#   ROOT_PASSWORD ORACLE_PASSWORD SYS_PASSWORD PDB_PASSWORD
#   DB_NAME PDB_NAME CDB ADG

for v in PROVIDER BOX_DISK_NUM VM1_NAME VM2_NAME SYSTEM_TIMEZONE \
         DB_SOFTWARE DB_VERSION DB_MAJOR DB_NAME \
         NODE1_PUBLIC_IP NODE2_PUBLIC_IP NODE1_PRIV_IP NODE2_PRIV_IP \
         ROOT_PASSWORD ORACLE_PASSWORD SYS_PASSWORD; do
  if [[ -z "${!v:-}" ]]; then
    echo "ERROR: required environment variable '${v}' is missing" >&2
    exit 1
  fi
done

DB_HOME="/u01/app/oracle/product/${DB_VERSION}/dbhome_1"
SETUP_ENV_DIR="/etc/opt/oracle-dg"
SETUP_ENV_FILE="${SETUP_ENV_DIR}/setup.env"

write_env_export() {
  local name="$1"
  local value="${2-}"
  printf 'export %s=%q\n' "${name}" "${value}"
}

# Build the runtime setup.env file that is sourced by the other scripts.
# Keep it on the guest filesystem rather than /vagrant so provider-specific
# synced-folder permissions do not block scripts that run as the oracle user.
install -d -m 0700 "${SETUP_ENV_DIR}"
( umask 077
  {
    printf '%s\n' \
      "# Generated by setup.sh. Do not edit by hand — will be overwritten on next 'vagrant up'." \
      '# Contains passwords.' \
      ''

    write_env_export PREFIX_NAME "${PREFIX_NAME}"
    printf '\n'

    write_env_export DB_SOFTWARE "${DB_SOFTWARE}"
    write_env_export DB_MAJOR "${DB_MAJOR}"
    write_env_export DB_VERSION "${DB_VERSION}"
    # Optional: empty unless a Release Update is configured in config/vagrant.yml.
    write_env_export OPATCH_SOFTWARE "${OPATCH_SOFTWARE:-}"
    write_env_export DB_RU_SOFTWARE  "${DB_RU_SOFTWARE:-}"
    printf '\n'

    write_env_export SYS_PASSWORD "${SYS_PASSWORD}"
    write_env_export PDB_PASSWORD "${PDB_PASSWORD:-}"
    printf '\n'

    write_env_export NODE1_PUBLIC_IP "${NODE1_PUBLIC_IP}"
    write_env_export NODE2_PUBLIC_IP "${NODE2_PUBLIC_IP}"
    write_env_export NODE1_PRIV_IP "${NODE1_PRIV_IP}"
    write_env_export NODE2_PRIV_IP "${NODE2_PRIV_IP}"
    printf '\n'

    write_env_export DOMAIN_NAME "${DOMAIN}"
    write_env_export NODE1_HOSTNAME "${VM1_NAME}"
    write_env_export NODE2_HOSTNAME "${VM2_NAME}"
    printf '%s\n' \
      'export NODE1_FQ_HOSTNAME="${NODE1_HOSTNAME}.${DOMAIN_NAME}"' \
      'export NODE2_FQ_HOSTNAME="${NODE2_HOSTNAME}.${DOMAIN_NAME}"' \
      'export NODE1_PRIVNAME="${NODE1_HOSTNAME}-priv"' \
      'export NODE2_PRIVNAME="${NODE2_HOSTNAME}-priv"' \
      'export NODE1_FQ_PRIVNAME="${NODE1_PRIVNAME}.${DOMAIN_NAME}"' \
      'export NODE2_FQ_PRIVNAME="${NODE2_PRIVNAME}.${DOMAIN_NAME}"' \
      ''

    write_env_export ORA_LANGUAGES "${ORA_LANGUAGES}"
    write_env_export ORA_INVENTORY '/u01/app/oraInventory'
    write_env_export DB_BASE '/u01/app/oracle'
    write_env_export DB_HOME "${DB_HOME}"
    write_env_export DB_NAME "${DB_NAME}"
    write_env_export PDB_NAME "${PDB_NAME:-}"
    write_env_export CDB "${CDB}"
    write_env_export ADG "${ADG}"
    printf '\n'

    write_env_export INFO '\033[0;34mINFO: \033[0m'
    write_env_export ERROR '\033[1;31mERROR: \033[0m'
    write_env_export SUCCESS '\033[1;32mSUCCESS: \033[0m'
  } > "${SETUP_ENV_FILE}"
)
chmod 0600 "${SETUP_ENV_FILE}"

# shellcheck disable=SC1091
. "${SCRIPT_DIR}/_common.sh"

log_section "Fixing locale warnings"
for line in 'LANG=en_US.utf-8' 'LC_ALL=en_US.utf-8'; do
  grep -qxF "${line}" /etc/environment || echo "${line}" >> /etc/environment
done

log_section "Setting system time zone to ${SYSTEM_TIMEZONE}"
timedatectl set-timezone "${SYSTEM_TIMEZONE}"

log_section "Installing OS packages"
bash "${SCRIPT_DIR}/01_install_os_packages.sh"

log_section "Setting up /u01 disk"
bash "${SCRIPT_DIR}/02_setup_u01.sh" "${BOX_DISK_NUM}" "${PROVIDER}"

log_section "Setting up oradata disks (/u02)"
ORADATA_DISK_OFFSET=$((BOX_DISK_NUM + 1))
bash "${SCRIPT_DIR}/03_setup_oradata_disks.sh" "${ORADATA_DISK_OFFSET}" "${PROVIDER}"

log_section "Setting up /etc/hosts and /etc/resolv.conf"
bash "${SCRIPT_DIR}/04_setup_hosts.sh"

log_section "Setting up OS users and groups"
bash "${SCRIPT_DIR}/05_setup_users.sh"

log_section "Granting oracle access to runtime provisioning env"
chgrp oinstall "${SETUP_ENV_DIR}" "${SETUP_ENV_FILE}"
chmod 0750 "${SETUP_ENV_DIR}"
chmod 0640 "${SETUP_ENV_FILE}"

log_section "Setting root and oracle account passwords"
# chpasswd reads from stdin — does not expose passwords via `ps`.
printf 'root:%s\n'   "${ROOT_PASSWORD}"   | chpasswd
printf 'oracle:%s\n' "${ORACLE_PASSWORD}" | chpasswd

log_section "Installing Oracle RDBMS software"
su - oracle -c "bash ${SCRIPT_DIR}/06_do_RDBMS_software_installation.sh"
bash "${ORA_INVENTORY}/orainstRoot.sh"
bash "${DB_HOME}/root.sh"

# Apply the optional Database RU to the freshly installed home, before any
# database exists. No-op unless env.opatch_software and env.db_ru_software are
# both set. Runs on both primary and standby so they start at the same patch
# level.
log_section "Patching RDBMS home (optional Release Update)"
su - oracle -c "bash ${SCRIPT_DIR}/09_patch_db_home.sh"

log_section "Configuring Oracle Net (listener, tnsnames)"
su - oracle -c "bash ${SCRIPT_DIR}/07_setup_OracleNet.sh"

current_host="$(hostname -s)"
if [[ "${current_host}" == "${NODE1_HOSTNAME}" ]]; then
  log_section "Configuring primary database"
  su - oracle -c "bash ${SCRIPT_DIR}/primary_DB_setup.sh"
elif [[ "${current_host}" == "${NODE2_HOSTNAME}" ]]; then
  log_section "Configuring standby database"
  su - oracle -c "bash ${SCRIPT_DIR}/standby_DB_setup.sh"
else
  log_error "hostname '${current_host}' matches neither primary (${NODE1_HOSTNAME}) nor standby (${NODE2_HOSTNAME})"
  exit 1
fi

log_section "Configuring database autostart"
bash "${SCRIPT_DIR}/08_setup_autostart.sh"

# Run user-defined post-setup scripts
log_section "Running user-defined post-setup scripts (userscripts/)"
shopt -s nullglob
for f in /vagrant/userscripts/*; do
  case "${f,,}" in
    *.sh)
      log_info "running ${f}"
      # shellcheck disable=SC1090
      . "${f}"
      log_info "done ${f}"
      ;;
    *.sql)
      log_info "running ${f} as SYS"
      su -l oracle -c "echo exit | sqlplus -s / as sysdba @\"${f}\""
      log_info "done ${f}"
      ;;
    /vagrant/userscripts/put_custom_scripts_here.txt)
      : # skip placeholder
      ;;
    *)
      log_info "ignoring ${f}"
      ;;
  esac
done

log_success "Provisioning complete"
