#
# Vagrantfile for Oracle Linux Cloud Native Environment
#
# Copyright (c) 1982-2019 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Deploys an Oracle Linux Cloud Native Environment
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#

# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile creates an Oracle Linux Cloud Native Environment and
# deploys the Kubernetes module to the master and worker nodes.
# VMs communicate via a private network:
#   - Operator: 192.168.99.100         (Optional, none by default)
#   - Master i: 192.168.99.(100+i)     (1 by default, 3 in HA mode)
#   - Worker i: 192.168.99.(110+i)     (2 by default)
#
# Optional plugins:
#     vagrant-hosts (maintains /etc/hosts for the VMs)
#     vagrant-env (use .env files for configuration)
#     vagrant-proxyconf (if you don't have direct access to the Internet)
#         see https://github.com/tmatilai/vagrant-proxyconf for configuration
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Box metadata location and box name
BOX_URL = "https://oracle.github.io/vagrant-boxes/boxes"
BOX_NAME = "oraclelinux/7"

# Define constants
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use vagrant-env plugin if available
  if Vagrant.has_plugin?("vagrant-env")
    config.env.load(".env.local", ".env") # enable the plugin
  end

  # Memory for the VMs (2GB)
  MEMORY = default_i("MEMORY", 2048)

  # Group VirtualBox containers
  VB_GROUP = default_s("VB_GROUP", "OLCNE")

  # Separate operator node for the Oracle Linux Cloud Native Environment
  # Platform API Server and Platform Agent (default is to install the
  # components on the (first) master node
  STANDALONE_OPERATOR = default_b('STANDALONE_OPERATOR', false)

  # Multi-master setup. Deploy 3 masters in HA mode.
  MULTI_MASTER = default_b('MULTI_MASTER', false)

  # Override number of masters to deploy
  # This should not be changed -- for development purpose
  NB_MASTERS = default_i('NB_MASTERS', MULTI_MASTER ? 3 : 1)

  # Number of worker nodes to provision
  NB_WORKERS = default_i('NB_WORKERS', 2)

  # Bind the kubectl proxy from the (first) master to the vagrant host
  BIND_PROXY = default_b('BIND_PROXY', false)

  # Additional yum channel to consider (e.g. local repo)
  YUM_REPO = default_s('YUM_REPO', '')

  # Add Oracle Linux Cloud Native Environment developer channel
  OLCNE_DEV = default_b('OLCNE_DEV', false)

  # Container registry for the Kubernetes module images
  REGISTRY_K8S = default_s('REGISTRY_K8S', 'container-registry.oracle.com/olcne')

  # Container registry for other Oracle Linux Cloud Native Environment images
  REGISTRY_OLCNE = default_s('REGISTRY_OLCNE', '')

  # Use specific component version (mainly used for development)
  OLCNE_VERSION = default_s('OLCNE_VERSION', '')
  K8S_VERSION = default_s('K8S_VERSION', '')
  NGINX_IMAGE = default_s('NGINX_IMAGE', 'nginx:1.12.2')

  # Verbose console
  VERBOSE = default_b('VERBOSE', false)
end

# Convenience methods
def default_s(key, default)
  ENV[key] && ! ENV[key].empty? ? ENV[key] : default
end

def default_i(key, default)
  default_s(key, default).to_i
end

def default_b(key, default)
  default_s(key, default).to_s.downcase == "true"
end

def ensure_scheme(url)
  (url =~ /.*:\/\// ? "" : "http://") + url
end

def provision_vm(vm, vm_args)
  args = vm_args.clone
  args.push("--multi-master") if MULTI_MASTER
  args.push("--repo", YUM_REPO) unless YUM_REPO == ""
  args.push("--olcne-dev") if OLCNE_DEV
  args.push("--registry-k8s", REGISTRY_K8S) if REGISTRY_K8S
  args.push("--registry-olcne", REGISTRY_OLCNE) if REGISTRY_OLCNE
  args.push("--olcne-version", OLCNE_VERSION) unless OLCNE_VERSION == ""
  args.push("--k8s-version", K8S_VERSION) unless K8S_VERSION == ""
  args.push("--verbose") if VERBOSE
  vm.provision "shell",
    path: "scripts/provision.sh",
    args: args
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # We start from the latest OL 7 Box
  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"

  # If we use the vagrant-proxyconf plugin, we should not proxy k8s/local IPs
  # Unfortunately we can't use CIDR with no_proxy, so we have to enumerate and
  # 'blacklist' *all* IPs
  if Vagrant.has_plugin?("vagrant-proxyconf")
    has_proxy = false
    ["http_proxy", "HTTP_PROXY"].each do |proxy_var|
      if proxy = ENV[proxy_var]
        puts "HTTP proxy: " + proxy
        config.proxy.http = ensure_scheme(proxy)
        has_proxy = true
        break
      end
    end

    ["https_proxy", "HTTPS_PROXY"].each do |proxy_var|
      if proxy = ENV[proxy_var]
        puts "HTTPS proxy: " + proxy
        config.proxy.https = ensure_scheme(proxy)
        has_proxy = true
        break
      end
    end

    if has_proxy
      # Only consider no_proxy if we have proxies defined.
      no_proxy = ""
      ["no_proxy", "NO_PROXY"].each do |proxy_var|
        if ENV[proxy_var]
          no_proxy = ENV[proxy_var]
          puts "No proxy: " + no_proxy
          no_proxy += ","
          break
        end
      end
      config.proxy.no_proxy = no_proxy + "localhost,.vagrant.vm," + (".0"..".255").to_a.join(",")
    end
  end

  # Provider-specific configuration -- VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
    vb.customize ["modifyvm", :id, "--groups", "/" + VB_GROUP]
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  # Workers provisioning
  workers = ""
  (1..NB_WORKERS).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.hostname = "worker#{i}.vagrant.vm"
      ip = 110 + i
      ip_addr = "192.168.99.#{ip}"
      workers += " #{ip_addr}"
      worker.vm.network "private_network", ip: ip_addr, auto_config: false
      if Vagrant.has_plugin?("vagrant-hosts")
        worker.vm.provision :hosts, :sync_hosts => true, :add_localhost_hostnames => false
      end
      # Provisioning: install stuff
      provision_vm(worker.vm, ["--worker", "--ip-addr", ip_addr])
    end
  end

  # Masters provisioning
  masters = ""
  NB_MASTERS.downto(1) do |i|
    config.vm.define "master#{i}" do |master|
      master.vm.hostname = "master#{i}.vagrant.vm"
      ip = 100 + i
      ip_addr = "192.168.99.#{ip}"
      masters += " #{ip_addr}"
      master.vm.network "private_network", ip: ip_addr, auto_config: false
      if Vagrant.has_plugin?("vagrant-hosts")
        master.vm.provision :hosts, :sync_hosts => true, :add_localhost_hostnames => false
      end
      if BIND_PROXY && i == 1
        # Bind kubectl proxy proxy port
        master.vm.network "forwarded_port", guest: 8001, host: 8001
      end
      # Provisioning: install stuff
      args = ["--master", "--ip-addr", ip_addr]
      if !STANDALONE_OPERATOR && i == 1
        args.push("--operator")
        args.push("--workers", workers)
        args.push("--masters", masters)
        args.push("--nginx-image", NGINX_IMAGE)
      end
      provision_vm(master.vm, args)
    end
  end

  # Operator node, if standalone
  if STANDALONE_OPERATOR
    config.vm.define "operator" do |operator|
      operator.vm.hostname = "operator.vagrant.vm"
      operator.vm.network "private_network", ip: "192.168.99.100"
      if Vagrant.has_plugin?("vagrant-hosts")
        operator.vm.provision :hosts, :sync_hosts => true, :add_localhost_hostnames => false
      end
      args = ["--operator", "--ip-addr", "192.168.99.100"]
      args.push("--workers", workers)
      args.push("--masters", masters)
      args.push("--nginx-image", NGINX_IMAGE)
      provision_vm(operator.vm, args)
    end
  end
end
