#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2018 Oracle and/or its affiliates. All rights reserved.
# 
# Since: January, 2018
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle database Vagrant virtual machine.
# 
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
# 

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# define hostname
NAME = "oracle-12201-vagrant"

unless Vagrant.has_plugin?("vagrant-env")
  puts 'Installing vagrant-env plugin...'
  if system('vagrant plugin install vagrant-env')
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort 'Installation of vagrant-env plugin has failed. Aborting.'
  end
end

# if .env doesn't exist, create it with default settings
unless File.exist?('.env')
  FileUtils.cp '.env.default', '.env'
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.env.enable
  config.vm.box = "ol7-latest"
  config.vm.box_url = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"
  config.vm.define NAME
  
  config.vm.box_check_update = false
  
  # change memory size
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.name = NAME
  end

  # VM hostname
  config.vm.hostname = NAME

  # Oracle port forwarding
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.network "forwarded_port", guest: 5500, host: 5500

  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/install.sh", env:
    {
       "ORACLE_BASE"         => ENV['VAGRANT_ORACLE_BASE'],
       "ORACLE_HOME"         => ENV['VAGRANT_ORACLE_HOME'],
       "ORACLE_SID"          => ENV['VAGRANT_ORACLE_SID'],
       "ORACLE_PDB"          => ENV['VAGRANT_ORACLE_PDB'],
       "ORACLE_CHARACTERSET" => ENV['VAGRANT_ORACLE_CHARACTERSET'],
       "ORACLE_EDITION"      => ENV['VAGRANT_ORACLE_EDITION'],
       "ORACLE_PWD"          => ENV['VAGRANT_ORACLE_PWD']
    }

end
