#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2018 Oracle and/or its affiliates. All rights reserved.
#
# Since: January, 2018
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle database Vagrant virtual machine.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Box metadata location and box name
BOX_URL = "https://oracle.github.io/vagrant-boxes/boxes"
BOX_NAME = "oraclelinux/7"

unless Vagrant.has_plugin?("vagrant-proxyconf")
  puts 'Installing vagrant-proxyconf Plugin...'
  system('vagrant plugin install vagrant-proxyconf')
end

# Define constants
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use vagrant-env plugin if available
  if Vagrant.has_plugin?("vagrant-env")
    config.env.load(".env.local", ".env") # enable the plugin
  end

  # VM name
  NAME = default_s('NAME', 'oracle-12201-vagrant')

  # Memory for the VM (in MB, 2048 MB = 2 GB)
  MEMORY = default_i('MEMORY', 2048)

  # VM time zone
  # If not specified, will be set to match host time zone (if possible)
  SYSTEM_TIMEZONE = default_s('SYSTEM_TIMEZONE', host_tz)

  # Oracle base directory
  # "VM_" prefix used to avoid conflict with host environment variable
  VM_ORACLE_BASE = default_s('VM_ORACLE_BASE', '/opt/oracle')

  # Oracle home directory
  # "VM_" prefix used to avoid conflict with host environment variable
  VM_ORACLE_HOME = default_s('VM_ORACLE_HOME', '/opt/oracle/product/12.2.0.1/dbhome_1')

  # Oracle SID
  # "VM_" prefix used to avoid conflict with host environment variable
  VM_ORACLE_SID = default_s('VM_ORACLE_SID', 'ORCLCDB')

  # PDB name
  ORACLE_PDB = default_s('ORACLE_PDB', 'ORCLPDB1')

  # Database character set
  ORACLE_CHARACTERSET = default_s('ORACLE_CHARACTERSET', 'AL32UTF8')

  # Oracle Database edition
  # Valid values are EE for Enterprise Edition or SE2 for Standard Edition 2
  ORACLE_EDITION = default_s('ORACLE_EDITION', 'EE')

  # Listener port
  LISTENER_PORT = default_i('LISTENER_PORT', 1521)

  # EM Express port
  EM_EXPRESS_PORT = default_i('EM_EXPRESS_PORT', 5500)

  # Oracle Database password for SYS, SYSTEM and PDBADMIN accounts
  # If left blank, the password will be generated automatically
  ORACLE_PWD = default_s('ORACLE_PWD', '')
end

# Convenience methods
def default_s(key, default)
  ENV[key] && ! ENV[key].empty? ? ENV[key] : default
end

def default_i(key, default)
  default_s(key, default).to_i
end

def host_tz
  # get host time zone for setting VM time zone
  # if host time zone isn't an integer hour offset from GMT, fall back to UTC
  offset_sec = Time.now.gmt_offset
  if (offset_sec % (60 * 60)) == 0
    offset_hr = ((offset_sec / 60) / 60)
    timezone_suffix = offset_hr >= 0 ? "-#{offset_hr.to_s}" : "+#{(-offset_hr).to_s}"
    'Etc/GMT' + timezone_suffix
  else
    'UTC'
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
  config.vm.define NAME

  # Provider-specific configuration -- VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.memory = MEMORY
    v.name = NAME
  end

  # add proxy configuration from host env - optional
  if Vagrant.has_plugin?("vagrant-proxyconf")
    puts "getting Proxy Configuration from Host..."
    if ENV["http_proxy"]
      puts "http_proxy: " + ENV["http_proxy"]
      config.proxy.http     = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      puts "https_proxy: " + ENV["https_proxy"]
      config.proxy.https    = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  # VM hostname
  config.vm.hostname = NAME

  # Oracle port forwarding
  config.vm.network "forwarded_port", guest: LISTENER_PORT, host: LISTENER_PORT
  config.vm.network "forwarded_port", guest: EM_EXPRESS_PORT, host: EM_EXPRESS_PORT

  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/install.sh", env:
    {
       "SYSTEM_TIMEZONE"     => SYSTEM_TIMEZONE,
       "ORACLE_BASE"         => VM_ORACLE_BASE,
       "ORACLE_HOME"         => VM_ORACLE_HOME,
       "ORACLE_SID"          => VM_ORACLE_SID,
       "ORACLE_PDB"          => ORACLE_PDB,
       "ORACLE_CHARACTERSET" => ORACLE_CHARACTERSET,
       "ORACLE_EDITION"      => ORACLE_EDITION,
       "LISTENER_PORT"       => LISTENER_PORT,
       "EM_EXPRESS_PORT"     => EM_EXPRESS_PORT,
       "ORACLE_PWD"          => ORACLE_PWD
    }

end
