#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2018 Oracle and/or its affiliates. All rights reserved.
# 
# Since: January, 2018
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle Linux virtual machine.
# 
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
# 

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "http://yum.oracle.com/boxes/oraclelinux/ol73/ol73.box"
  
  config.vm.box_check_update = false
  
  # change memory size
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.name = "ol7-vagrant"
  end

  # VM hostname
  config.vm.hostname = "ol7-vagrant"
  
  # Oracle port forwarding
  config.vm.network "forwarded_port", guest: 22, host: 2220

  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/install.sh"

end
