#!/usr/bin/env bash
#------------------------------------------------------------------------------
# LICENSE UPL 1.0
# Copyright (c) 1982-2026 Oracle and/or its affiliates. All rights reserved.
#
# 08_setup_OracleNet.sh
#   Writes tnsnames.ora / listener.ora / sqlnet.ora for the True Cache node and
#   starts the local listener. The tnsnames includes an alias to the source
#   database (SDB) that redo is fetched from. Runs as the oracle user.
#------------------------------------------------------------------------------
. /vagrant/scripts/_common.sh
require_user oracle
require_var DB_HOME
require_var DB_BASE
require_var NODE1_HOSTNAME
require_var SDB_HOST_NAME
require_var SDB_SERVICE_NAME
require_var SDB_SERVICE_PORT
require_var DB_UNIQUE_NAME
require_var INSTANCE_NAME

net_admin="${DB_HOME}/network/admin"
mkdir -p "${net_admin}"

log_section "Writing tnsnames.ora"
cat > "${net_admin}/tnsnames.ora" <<EOF
# Generated by Vagrant provisioner — do not edit.
LISTENER = (ADDRESS = (PROTOCOL = TCP)(HOST = ${NODE1_HOSTNAME})(PORT = 1521))

${SDB_SERVICE_NAME} =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${SDB_HOST_NAME})(PORT = ${SDB_SERVICE_PORT}))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = ${SDB_SERVICE_NAME})
    )
  )

${DB_UNIQUE_NAME} =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${NODE1_HOSTNAME})(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = ${DB_UNIQUE_NAME})
    )
  )
EOF

log_section "Writing listener.ora"
cat > "${net_admin}/listener.ora" <<EOF
# Generated by Vagrant provisioner — do not edit.
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${NODE1_HOSTNAME})(PORT = 1521))
    )
  )

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = ${DB_UNIQUE_NAME})
      (ORACLE_HOME   = ${DB_HOME})
      (SID_NAME      = ${INSTANCE_NAME})
    )
  )

ADR_BASE_LISTENER = ${DB_BASE}
INBOUND_CONNECT_TIMEOUT_LISTENER = 400
EOF

log_section "Writing sqlnet.ora"
cat > "${net_admin}/sqlnet.ora" <<'EOF'
# Generated by Vagrant provisioner — do not edit.
SQLNET.INBOUND_CONNECT_TIMEOUT = 400
EOF

log_section "Starting listener"
"${DB_HOME}/bin/lsnrctl" start
