#!/usr/bin/env bash
#------------------------------------------------------------------------------
# LICENSE UPL 1.0
# Copyright (c) 1982-2026 Oracle and/or its affiliates. All rights reserved.
#
# setup.sh
#   Orchestrator for the Oracle True Cache single-node provisioning flow.
#   Invoked by Vagrantfile on host1.
#
#   Author: Ruggero Citton <ruggero.citton@oracle.com>
#           RAC Pack, Cloud Innovation and Solution Engineering Team
#------------------------------------------------------------------------------

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

SCRIPT_DIR="/vagrant/scripts"

# Environment vars passed in by Vagrantfile (env: { ... }):
#   PROVIDER BOX_DISK_NUM VM1_NAME SYSTEM_TIMEZONE PREFIX_NAME
#   DB_SOFTWARE OPATCH_SOFTWARE DB_RU_SOFTWARE DB_VERSION DB_MAJOR ORA_LANGUAGES
#   NODE1_PUBLIC_IP NODE1_PRIV_IP DNS_PUBLIC_IP DOMAIN_NAME
#   ROOT_PASSWORD ORACLE_PASSWORD SYS_PASSWORD PDB_PASSWORD
#   SDB_HOST_NAME SDB_SERVICE_NAME SDB_SERVICE_PORT
#   DB_FILES DB_UNIQUE_NAME INSTANCE_NAME FAL_CLIENT FAL_SERVER
#   LOCAL_LISTENER SGA_TARGET HUGEPAGES

for v in PROVIDER BOX_DISK_NUM VM1_NAME SYSTEM_TIMEZONE PREFIX_NAME \
         DB_SOFTWARE DB_VERSION DB_MAJOR \
         NODE1_PUBLIC_IP NODE1_PRIV_IP \
         ROOT_PASSWORD ORACLE_PASSWORD \
         SDB_HOST_NAME SDB_SERVICE_NAME \
         DB_UNIQUE_NAME INSTANCE_NAME; do
  if [[ -z "${!v:-}" ]]; then
    echo "ERROR: required environment variable '${v}' is missing" >&2
    exit 1
  fi
done

DB_HOME="/u01/app/oracle/product/${DB_VERSION}/dbhome_1"
SETUP_ENV_DIR="/etc/opt/oracle-tc"
SETUP_ENV_FILE="${SETUP_ENV_DIR}/setup.env"

write_env_export() {
  local name="$1"
  local value="${2-}"
  printf 'export %s=%q\n' "${name}" "${value}"
}

# Build the runtime setup.env file that is sourced by the other scripts (via
# _common.sh). Keep it on the guest filesystem rather than /vagrant so
# provider-specific synced-folder permissions do not block scripts that run as
# the oracle user.
install -d -m 0700 "${SETUP_ENV_DIR}"
( umask 077
  {
    printf '%s\n' \
      "# Generated by setup.sh. Do not edit by hand — will be overwritten on next 'vagrant up'." \
      '# Contains passwords.' \
      ''

    write_env_export PREFIX_NAME "${PREFIX_NAME}"
    printf '\n'

    write_env_export DB_SOFTWARE "${DB_SOFTWARE}"
    write_env_export DB_MAJOR "${DB_MAJOR}"
    write_env_export DB_VERSION "${DB_VERSION}"
    # Optional: empty unless a Release Update is configured in config/vagrant.yml.
    write_env_export OPATCH_SOFTWARE "${OPATCH_SOFTWARE:-}"
    write_env_export DB_RU_SOFTWARE  "${DB_RU_SOFTWARE:-}"
    printf '\n'

    write_env_export SYS_PASSWORD "${SYS_PASSWORD:-}"
    write_env_export PDB_PASSWORD "${PDB_PASSWORD:-}"
    printf '\n'

    write_env_export DNS_PUBLIC_IP "${DNS_PUBLIC_IP:-}"
    write_env_export NODE1_PUBLIC_IP "${NODE1_PUBLIC_IP}"
    write_env_export NODE1_PRIV_IP "${NODE1_PRIV_IP}"
    printf '\n'

    write_env_export DOMAIN_NAME "${DOMAIN_NAME}"
    write_env_export NODE1_HOSTNAME "${VM1_NAME}"
    printf '%s\n' \
      'export NODE1_FQ_HOSTNAME="${NODE1_HOSTNAME}.${DOMAIN_NAME}"' \
      'export NODE1_PRIVNAME="${NODE1_HOSTNAME}-priv"' \
      'export NODE1_FQ_PRIVNAME="${NODE1_PRIVNAME}.${DOMAIN_NAME}"' \
      ''

    write_env_export ORA_LANGUAGES "${ORA_LANGUAGES}"
    write_env_export ORA_INVENTORY '/u01/app/oraInventory'
    write_env_export DB_BASE '/u01/app/oracle'
    write_env_export DB_HOME "${DB_HOME}"
    printf '\n'

    # ---- Oracle True Cache specific settings ----
    write_env_export SDB_HOST_NAME "${SDB_HOST_NAME}"
    write_env_export SDB_SERVICE_NAME "${SDB_SERVICE_NAME}"
    write_env_export SDB_SERVICE_PORT "${SDB_SERVICE_PORT}"
    write_env_export ORACLE_SID "${INSTANCE_NAME}"
    write_env_export DB_FILES "${DB_FILES}"
    write_env_export DB_UNIQUE_NAME "${DB_UNIQUE_NAME}"
    write_env_export INSTANCE_NAME "${INSTANCE_NAME}"
    write_env_export FAL_CLIENT "${FAL_CLIENT}"
    write_env_export FAL_SERVER "${FAL_SERVER}"
    write_env_export LOCAL_LISTENER "${LOCAL_LISTENER}"
    write_env_export SGA_TARGET "${SGA_TARGET}"
    write_env_export HUGEPAGES "${HUGEPAGES}"
    printf '\n'

    write_env_export INFO '\033[0;34mINFO: \033[0m'
    write_env_export ERROR '\033[1;31mERROR: \033[0m'
    write_env_export SUCCESS '\033[1;32mSUCCESS: \033[0m'
  } > "${SETUP_ENV_FILE}"
)
chmod 0600 "${SETUP_ENV_FILE}"

# shellcheck disable=SC1091
. "${SCRIPT_DIR}/_common.sh"

log_section "Fixing locale warnings"
for line in 'LANG=en_US.utf-8' 'LC_ALL=en_US.utf-8'; do
  grep -qxF "${line}" /etc/environment || echo "${line}" >> /etc/environment
done

log_section "Setting system time zone to ${SYSTEM_TIMEZONE}"
timedatectl set-timezone "${SYSTEM_TIMEZONE}"

log_section "Installing OS packages"
bash "${SCRIPT_DIR}/01_install_os_packages.sh"

log_section "Setting up /u01 disk"
bash "${SCRIPT_DIR}/02_setup_u01.sh" "${BOX_DISK_NUM}" "${PROVIDER}"

log_section "Setting up oradata disks (/u02)"
ORADATA_DISK_OFFSET=$((BOX_DISK_NUM + 1))
bash "${SCRIPT_DIR}/03_setup_oradata_disks.sh" "${ORADATA_DISK_OFFSET}" "${PROVIDER}"

log_section "Setting up /etc/hosts and /etc/resolv.conf"
bash "${SCRIPT_DIR}/04_setup_hosts.sh"

log_section "Setting up OS users and groups"
bash "${SCRIPT_DIR}/05_setup_users.sh"

log_section "Granting oracle access to runtime provisioning env"
chgrp oinstall "${SETUP_ENV_DIR}" "${SETUP_ENV_FILE}"
chmod 0750 "${SETUP_ENV_DIR}"
chmod 0640 "${SETUP_ENV_FILE}"

log_section "Setting root and oracle account passwords"
# chpasswd reads from stdin — does not expose passwords via `ps`.
printf 'root:%s\n'   "${ROOT_PASSWORD}"   | chpasswd
printf 'oracle:%s\n' "${ORACLE_PASSWORD}" | chpasswd

log_section "Installing Oracle RDBMS software"
su - oracle -c "bash ${SCRIPT_DIR}/06_do_RDBMS_software_installation.sh"
bash "${ORA_INVENTORY}/orainstRoot.sh"
bash "${DB_HOME}/root.sh"
rm -fr /u01/app/stage

# Apply the optional Database RU to the freshly installed home, before the True
# Cache instance is created. No-op unless env.opatch_software and
# env.db_ru_software are both set.
log_section "Patching RDBMS home (optional Release Update)"
su - oracle -c "bash ${SCRIPT_DIR}/07_patch_db_home.sh"

log_section "Configuring Oracle Net (listener, tnsnames)"
su - oracle -c "bash ${SCRIPT_DIR}/08_setup_OracleNet.sh"

log_section "Configuring Oracle True Cache instance"
su - oracle -c "bash ${SCRIPT_DIR}/09_TrueCache_setup.sh"

log_section "Configuring database autostart"
bash "${SCRIPT_DIR}/10_setup_autostart.sh"

# Run user-defined post-setup scripts
log_section "Running user-defined post-setup scripts (userscripts/)"
shopt -s nullglob
for f in /vagrant/userscripts/*; do
  case "${f,,}" in
    *.sh)
      log_info "running ${f}"
      # shellcheck disable=SC1090
      . "${f}"
      log_info "done ${f}"
      ;;
    *.sql)
      log_info "running ${f} as SYS"
      su -l oracle -c "echo exit | sqlplus -s / as sysdba @\"${f}\""
      log_info "done ${f}"
      ;;
    /vagrant/userscripts/put_custom_scripts_here.txt)
      : # skip placeholder
      ;;
    *)
      log_info "ignoring ${f}"
      ;;
  esac
done

log_success "Provisioning complete"
