---
version: "3.8"
networks:
  shard_pub1_nw:
    name: shard_pub1_nw
    driver: bridge
    ipam:
      config:
        - subnet: "${NETWORK_SUBNET}"
secrets:
  pwdsecret:
    external: pwdsecret
  keysecret:
    external: keysecret
services:
  catalog_db:
    container_name: ${CAT_CONTAINER_NAME}
    privileged: ${CONTAINER_PRIVILEGED_FLAG}
    hostname: ${CAT_HOSTNAME}
    image: ${SIDB_IMAGE}
    dns_search: ${DNS_SEARCH}
    restart: ${CONTAINER_RESTART_POLICY}
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${PODMANVOLLOC}/dbfiles/CATALOG:/opt/oracle/oradata
      - /opt/containers/shard_host_file:/etc/hosts
    environment:
      SHARD_SETUP: ${CAT_SHARD_SETUP}
      DOMAIN: ${DOMAIN}
      ORACLE_SID: ${CAT_SID}
      ORACLE_PDB: ${CAT_PDB"}
      ORACLE_FREE_PDB: ${CAT_FREE_PDB}
      DB_UNIQUE_NAME: ${CAT_CDB}
      OP_TYPE: ${CATALOG_OP_TYPE}
      COMMON_OS_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      ENABLE_ARCHIVELOG: ${CATALOG_ARCHIVELOG}
    networks:
      shard_pub1_nw:
        ipv4_address: ${LOCAL_NETWORK}.102
  shard1_db:
    container_name: ${SHARD1_CONTAINER_NAME}
    privileged: ${CONTAINER_PRIVILEGED_FLAG}
    hostname: ${SHARD1_HOSTNAME}
    image: ${SIDB_IMAGE}
    dns_search: ${DNS_SEARCH}
    restart: ${CONTAINER_RESTART_POLICY}
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${PODMANVOLLOC}/dbfiles/ORCL1CDB:/opt/oracle/oradata
      - /opt/containers/shard_host_file:/etc/hosts
    environment:
      SHARD_SETUP: ${SHARD1_SHARD_SETUP}
      DOMAIN: ${DOMAIN}
      ORACLE_SID: ${SHARD1_SID}
      ORACLE_PDB: ${SHARD1_PDB"}
      ORACLE_FREE_PDB: ${SHARD1_FREE_PDB}
      DB_UNIQUE_NAME: ${SHARD1_CDB}
      OP_TYPE: ${ALLSHARD_OP_TYPE}
      COMMON_OS_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      ENABLE_ARCHIVELOG: ${SHARD_ARCHIVELOG}
    networks:
      shard_pub1_nw:
        ipv4_address: ${LOCAL_NETWORK}.103
  shard2_db:
    container_name: ${SHARD2_CONTAINER_NAME}
    privileged: ${CONTAINER_PRIVILEGED_FLAG}
    hostname: ${SHARD2_HOSTNAME}
    image: ${SIDB_IMAGE}
    dns_search: ${DNS_SEARCH}
    restart: ${CONTAINER_RESTART_POLICY}
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${PODMANVOLLOC}/dbfiles/ORCL2CDB:/opt/oracle/oradata
      - /opt/containers/shard_host_file:/etc/hosts
    environment:
      SHARD_SETUP: ${SHARD2_SHARD_SETUP}
      DOMAIN: ${DOMAIN}
      ORACLE_SID: ${SHARD2_SID}
      ORACLE_PDB: ${SHARD2_PDB"}
      ORACLE_FREE_PDB: ${SHARD2_FREE_PDB}
      DB_UNIQUE_NAME: ${SHARD2_CDB}
      OP_TYPE: ${ALLSHARD_OP_TYPE}
      COMMON_OS_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      ENABLE_ARCHIVELOG: ${SHARD_ARCHIVELOG}
    networks:
      shard_pub1_nw:
        ipv4_address: ${LOCAL_NETWORK}.104
  shard3_db:
    container_name: ${SHARD3_CONTAINER_NAME}
    privileged: ${CONTAINER_PRIVILEGED_FLAG}
    hostname: ${SHARD3_HOSTNAME}
    image: ${SIDB_IMAGE}
    dns_search: ${DNS_SEARCH}
    restart: ${CONTAINER_RESTART_POLICY}
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${PODMANVOLLOC}/dbfiles/ORCL3CDB:/opt/oracle/oradata
      - /opt/containers/shard_host_file:/etc/hosts
    environment:
      SHARD_SETUP: ${SHARD3_SHARD_SETUP}
      DOMAIN: ${DOMAIN}
      ORACLE_SID: ${SHARD3_SID}
      ORACLE_PDB: ${SHARD3_PDB"}
      ORACLE_FREE_PDB: ${SHARD3_FREE_PDB}
      DB_UNIQUE_NAME: ${SHARD3_CDB}
      OP_TYPE: ${ALLSHARD_OP_TYPE}
      COMMON_OS_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      ENABLE_ARCHIVELOG: ${SHARD_ARCHIVELOG}
    networks:
      shard_pub1_nw:
        ipv4_address: ${LOCAL_NETWORK}.105
  shard4_db:
    container_name: ${SHARD4_CONTAINER_NAME}
    privileged: ${CONTAINER_PRIVILEGED_FLAG}
    hostname: ${SHARD4_HOSTNAME}
    image: ${SIDB_IMAGE}
    dns_search: ${DNS_SEARCH}
    restart: ${CONTAINER_RESTART_POLICY}
    dbEdition: ${DB_EDITION}
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${PODMANVOLLOC}/dbfiles/ORCL4CDB:/opt/oracle/oradata
      - /opt/containers/shard_host_file:/etc/hosts
    environment:
      SHARD_SETUP: ${SHARD4_SHARD_SETUP}
      DOMAIN: ${DOMAIN}
      ORACLE_SID: ${SHARD4_SID}
      ORACLE_PDB: ${SHARD4_PDB"}
      ORACLE_FREE_PDB: ${SHARD4_FREE_PDB}
      DB_UNIQUE_NAME: ${SHARD4_CDB}
      OP_TYPE: ${ALLSHARD_OP_TYPE}
      COMMON_OS_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      ENABLE_ARCHIVELOG: ${SHARD_ARCHIVELOG}
    networks:
      shard_pub1_nw:
        ipv4_address: ${LOCAL_NETWORK}.106
  primary_gsm:
    container_name: ${PRIMARY_GSM_CONTAINER_NAME}
    privileged: ${CONTAINER_PRIVILEGED_FLAG}
    hostname: ${PRIMARY_GSM_HOSTNAME}
    image: ${GSM_IMAGE}
    dns_search: ${DNS_SEARCH}
    restart: ${CONTAINER_RESTART_POLICY}
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${PODMANVOLLOC}/dbfiles/GSMDATA:/opt/oracle/gsmdata
      - /opt/containers/shard_host_file:/etc/hosts
    environment:
      DOMAIN: ${DOMAIN}
      SHARD_DIRECTOR_PARAMS: ${PRIMARY_SHARD_DIRECTOR_PARAMS}
      SHARD1_GROUP_PARAMS: ${PRIMARY_SHARD1_GROUP_PARAMS}
      CATALOG_PARAMS: ${PRIMARY_CATALOG_PARAMS}
      SHARD1_PARAMS: ${PRIMARY_SHARD1_PARAMS}
      SHARD2_PARAMS: ${PRIMARY_SHARD2_PARAMS}
      SHARD3_PARAMS: ${STANDBY_SHARD3_PARAMS}
      SHARD4_PARAMS: ${STANDBY_SHARD4_PARAMS}
      SERVICE1_PARAMS: ${PRIMARY_SERVICE1_PARAMS}
      SERVICE2_PARAMS: ${PRIMARY_SERVICE2_PARAMS}
      COMMON_OS_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      MASTER_GSM: "TRUE"
      OP_TYPE: ${GSM_OP_TYPE}
    networks:
      shard_pub1_nw:
        ipv4_address: ${LOCAL_NETWORK}.100
  standby_gsm:
    container_name: ${STANDBY_GSM_CONTAINER_NAME}
    privileged: ${CONTAINER_PRIVILEGED_FLAG}
    hostname: ${STANDBY_GSM_HOSTNAME}
    image: ${GSM_IMAGE}
    dns_search: ${DNS_SEARCH}
    restart: ${CONTAINER_RESTART_POLICY}
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${PODMANVOLLOC}/dbfiles/GSM2DATA:/opt/oracle/gsmdata
      - /opt/containers/shard_host_file:/etc/hosts
    environment:
      SHARD_SETUP: ${STANDBY_GSM_SHARD_SETUP}
      DOMAIN: ${DOMAIN}
      SHARD_DIRECTOR_PARAMS: ${STANDBY_SHARD_DIRECTOR_PARAMS}
      SHARD1_GROUP_PARAMS: ${STANDBY_SHARD1_GROUP_PARAMS}
      CATALOG_PARAMS: ${STANDBY_CATALOG_PARAMS}
      SHARD1_PARAMS: ${STANDBY_SHARD1_PARAMS}
      SHARD2_PARAMS: ${STANDBY_SHARD2_PARAMS}
      SHARD3_PARAMS: ${STANDBY_SHARD3_PARAMS}
      SHARD4_PARAMS: ${STANDBY_SHARD4_PARAMS}
      SERVICE1_PARAMS: ${STANDBY_SERVICE1_PARAMS}
      SERVICE2_PARAMS: ${STANDBY_SERVICE2_PARAMS}
      COMMON_OS_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      OP_TYPE: ${GSM_OP_TYPE}
    networks:
      shard_pub1_nw:
        ipv4_address: ${LOCAL_NETWORK}.101
